GET http://localhost:5194/

###
# @name createSession
POST http://localhost:5194/chat/sessions

###
POST http://localhost:5194/chat/sessions/{{createSession.response.body.sessionId}}/messages
Content-Type: application/json

{
    "message": "Shut up, I am working!"
}

###
POST http://localhost:5194/chat/sessions/{{createSession.response.body.sessionId}}/run

